### ISSUE TITLE
Which version of pyside depends on?

### ISSUE THREAD

**Issue by moxiaonai** [birolkuyumcu/offline-netscope#1]
I installed QT@4.5 and PySide@1.2.4  but it loged error msg "No module named QtWebKit"

**Comment by birolkuyumcu** [comment]
i also use 1.2.4 version 
this is documentation 
https://pyside.github.io/docs/pyside/PySide/QtWebKit/index.html
so there is a module named QtWebKit
check your packages

**Comment by moxiaonai** [comment]
@birolkuyumcu  thanks for your reply，i'll read it and try again, have fun!
